### ISSUE TITLE
Trying to approve and disapprove

### ISSUE THREAD

**Issue by TDFvance** [realbig/RBMC_PL_WOOCOMMERCEPRODUCTVENDORS#17] opened 2015-06-02 16:45 UTC
I've tried to approve and disapprove all of these items on this Vendor Updates page, and it doesn't do anything when I push the X or the checkmark button.
![k5error2](https://cloud.githubusercontent.com/assets/12396651/7941443/4bd13eee-0925-11e5-8e23-21408e0f49e8.JPG)

**Comment by TDFvance** [comment] 2015-06-02 17:10
I added a new vendor and was able to approve him. Perhaps there are just some lingering items that the system doesn't know how to handle. If we remove these, that might work.

**Comment by joelworsham** [comment] 2015-06-11 18:54
Fixed in a12105f.

Made invalid modification requests automatically disappear.

**Closed as completed by joelworsham** 2015-06-11 18:54 UTC

**Comment by TDFvance** [comment] 2015-06-23 16:53
This appears to be malfunctioning. I have a vendor awaiting approval that I am unable to approve.

**Comment by TDFvance** [comment] 2015-06-23 16:56
![vendormodifications](https://cloud.githubusercontent.com/assets/12396651/8311858/3be800fc-19a7-11e5-9504-cd34b96108bb.JPG)

**Comment by joelworsham** [comment] 2015-06-23 16:57
That is intended behavior. If you were able to delete that, then you would never be able to change your mind and approve it in the future.

We could perhaps figure out an alternative solution, but this is currently intended behavior.

**Comment by TDFvance** [comment] 2015-06-23 16:58
I'm trying to approve a valid new distributor and it won't approve. I've marked the check mark.

**Comment by joelworsham** [comment] 2015-06-23 16:58
OH. I misread, I thought you meant you were trying to remove it. I will look into this.

**Comment by TDFvance** [comment] 2015-06-23 16:58
Thanks. I am training them on the system in a little bit. I was walking through my training on how to create a new distributor and found I wasn't able to make them live.

**Comment by joelworsham** [comment] 2015-06-23 17:00
Is this on the live site? I don't see this pending change.

https://k5skinnutrition.com/wp-admin/admin.php?page=vendor-updates

**Comment by TDFvance** [comment] 2015-06-23 17:01
It's gone now. I wonder if it was just being glitchy and slow. It appears to have approved now.

Even when I refreshed the page, it was still sitting there unapproved and the vendor's store wasn't coming up yet either. Not sure what was going on.

**Comment by joelworsham** [comment] 2015-06-23 17:02
Hmm, the site does tend to load slowly occasionally. So perhaps it was just loading slowly. If this problem happens again, feel free to let me know.

**Comment by TDFvance** [comment] 2015-06-23 17:02
Ok. Thanks!

**Comment by TDFvance** [comment] 2015-06-23 17:41
It is not approving. Just sometimes. Can you double check it for me? Maybe it’s timing out.

**Comment by joelworsham** [comment] 2015-06-23 17:56
I just attempted to approve the vendor, and it worked for me.
